channels:
  sources:
  - conda-forge
  - guyer
  - defaults
  targets:
  - [guyer, main]
travis:
  secure:
    BINSTAR_TOKEN: JeDKM9w1rJZYAyIMfAevjGPkPXo4ARS/RQ8C6B+hpPpVnao7gQBv2Q7gD5anpg3smkN5gNcInpq9n9ShvAqItzj2oCUnTKdN0HouL6gxjtkxgnMC4K50OetYd3CP+u3QX0UxLRkw/7KcEjmfaq4ENXHMLmZZOzcQw6Tw0bCUtOSZs9abeOgf221rOLTkKlGkwY1A6gveGHmOVGIEkpoGd7ghKGRnzH1cD3JQkoIgPIMp9vhE6Z7oniRtl+nnbNr8knZjy9vBm7X89r0RUUkSjf3C2HYlHcwi/cmcU8XM7O6fw0aecaFSgrEp3idUZHKAQRAL4NP1hRhuM9aW+PXQ0gI4U4+etKUTWe4yhieGngQXJgwUiro6AZnfnJ7pYRprLTQhsFXNbOq15disyH7sMccS/GCqRZV8fwlCFALMExAGdGVerzU3Cv9qnCHLZD9jaX3tSCIg53n50l/yIwH2E9XhRmU9Z3aYy8Rh3PvgnKO/uKea6iqNsbLOB06TlY1N/BeewBs6FatQtVlnYkuJkMoJZXNG1W2UjPtZ37yPtqU1el+46nmAI5vm/3SClQGmkLh0K2zye94Q7ZB/evk/y1pIQeNKPbk3FbUhExd4UoShLIjZ6+3sfPRUgKo5sMtH6fBcpNA4RBVH7PvdtWqbxNXs5z7qoGj8OURzzwAH+EA=
appveyor:
  secure:
    BINSTAR_TOKEN: 26P3JkJ/iVPaW6c+5V5XYJ6H9Jaw/iYr0SU7KqDJCRk2+ScBP0rsvIyDOxDE9let
