channels:
  sources:
    - conda-forge
    - guyer
    - defaults
  targets:
    - [guyer, main]
travis:
  secure:
    BINSTAR_TOKEN: TRsIKAlpVnC81Cet0nZrMVrL6Ddrbt+8YJebvTIRptqERTfzNtX04pxKjutO9ukUU1qM8AqFLLMi5u8SfYyzBXHWiP1bdkpqOBknafpX/r4h7ifSw9kt2MARdHy5oywwxamILgmoG83hdVAHbulVk8W0XEGMt1HDyivgy4cdWNuKDBNuGTdW3ipf0gIKa3Ttuc61xLrVBVsdBi2+nuifPsUF0GS2bC5y8PpBF464UygxgYaNGHOgLy9+18vcVFd9OFVPWev+Ex9GmyZw/6is1hqwvCoXRd2xe18LqdsadYURh2sFMSOxNPt4xKGc2BuSOhTKgg7MnCiCCnsF110Os84eXUVWjhaSwmn3Uu8Fs3hjHIuVp/vDTzH9y4i4Q3sMeb2iz7f7HIwWbd1cHf/0e1rceb+nMkZozlDsBfwpL7EcWlOBCJwH9wzmCtkA5Yztdo3QKEOpRqDuBAXP2r0SQuDrC9CL0ZPSfqFN6imp9OWpfc4rCS7mKvvxmkbKK7ChBdv7VDG0RRi5++hg7Vc/4Zbe04lrWb9zEGMLI6fsPaeluE7/JarKnGCV1zNk2bOP8dMDGfm2Ez8A0VTPDHyIJv1FBKoVLDMabJ6KBzsOiWgm4T01ypZY8gwB2UbjdgS6uDfT9YK5oGhKYRXk1smxln4gyVOSkqol9ZPit9mpmF4=
appveyor:
  secure:
    BINSTAR_TOKEN: X89+MTZivHBAXLSEy/G8CnQu+orYtiX/vKbQ7w7Wqbhv11U+EPgW+otnBaeJ6JCY
